name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --package-path src/AudioPreviewGD
      - name: Test
        run: swift test --package-path src/AudioPreviewGD
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            src/AudioPreviewGD/.build/**/libAudioPreviewGD.so
            src/AudioPreviewGD/.build/**/libAudioPreviewGD.dylib
            src/AudioPreviewGD/.build/**/AudioPreviewGD.dll
