name: Build

on: [push]

permissions:
  contents: write

env:
  # For Windows/Linux
  swift-version: "5.10.1"
  # For macOS
  xcode-version-aarch64: "15.3"
  xcode-version-x86_64: "15.2"

# !! HERE BE DRAGONS !!
jobs:
  bundle:
    name: Generate bundle
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          run-id: "10017335843"
      - name: Aggregate artifacts
        run: |
          ls -lR
          mkdir addons/audio_preview_gd/bin
          cp ubuntu-latest/libAudioPreviewGD.so windows-latest/AudioPreviewGD.dll addons/audio_preview_gd/bin
          cp macos-latest/libAudioPreview.dylib addons/audio_preview_gd/bin/libAudioPreview-aarch64.dylib
          cp macos-13/libAudioPreview.dylib addons/audio_preview_gd/bin/libAudioPreview-x86_64.dylib
          zip -r9 audio_preview_gd.zip addons
          echo commit_count=$(git rev-list --count HEAD) >> "$GITHUB_ENV"
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: audio_preview_gd.zip
          tag_name: "1.${{ env.commit_count }}"
          generate_release_notes: true
          prerelease: true
          fail_on_unmatched_files: true
